# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'Bylaws.md'
      - name: Move output
        run: mv ${{ steps.publish-document.outputs.pdf }} Bylaws.pdf
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Github Actions
          author_email: noreply@github.com
          message: "Auto-generate PDF"
          add: "Bylaws.pdf"

